name: build
jobs:
    windows:
        runs-on: windows-2019
        steps:
            - name: checkout
                uses: actions/checkout@v1
            - name: make project
                working-directory: projects
                run: genie.exe --static-plugins vs2019 
            - name: build engine
                working-directory: projects
                run: msbuild.exe tmp/vs2019/LumixEngine.sln /p:Configuration=RelWithDebInfo
            