name: build
on: [push]
jobs:
    windows:
        runs-on: windows-2019
        steps:
            - uses: actions/checkout@v1
              with:
                fetch-depth: 1
            - name: make project
              working-directory: projects
              run: ./genie.exe --static-plugins vs2019 
            - name: build engine
              working-directory: projects
              shell: cmd
              run: |
                "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe" tmp/vs2019/LumixEngine.sln /p:Configuration=RelWithDebInfo
    linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
              with:
                fetch-depth: 1
            - name: make project
              working-directory: projects
              run: ./genie --static-plugins gmake
            - name: install packages
              run: |
                sudo apt-get update
                sudo apt-get install mesa-common-dev
                sudo apt-get install libasound2-dev
            - name: build engine
              working-directory: projects/tmp/gmake
              run: |
                make engine
                make audio
                make animation
                make physics
                make navigation
                make gui
                make lua_script
                make renderer
                make editor
    static_analysis:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v1
            with:
              fetch-depth: 1

          - name: Install Dependencies
            env:
              PVS_STUDIO_LICENSE: ${{ secrets.PVS_STUDIO_LICENSE }}
            run: |
              if [[ "$PVS_STUDIO_LICENSE" != "" ]];
              then
                echo "$PVS_STUDIO_LICENSE" > pvs-studio.lic
                wget -q https://files.viva64.com/etc/pubkey.txt
                sudo apt-key add pubkey.txt
                sudo wget -O /etc/apt/sources.list.d/viva64.list https://files.viva64.com/etc/viva64.list
                sudo apt-get update
                sudo apt-get install -y pvs-studio
              fi
          - name: PVS-Studio static analysis
            run: |
              if [[ ! -f pvs-studio.lic ]];
              then
                echo "PVS Studio license is missing. No analysis will be performed."
                echo "If you have a PVS Studio license please create a project secret named PVS_STUDIO_LICENSE with your license."
                echo "You may use a free license. More information at https://www.viva64.com/en/b/0457/"
                exit 0
              fi
              cd projects
              ./genie --static-plugins gmake
              cd tmp/gmake
              pvs-studio-analyzer trace -- make EXTRA_WARNINGS=1
              pvs-studio-analyzer analyze -e ../../../src/engine/engine.cpp -l ../../pvs-studio.lic -o pvs-studio.log
              plog-converter -a 'GA:1,2;OP:1' -t errorfile -w pvs-studio.log
